name = "StringUnits"
uuid = "aae3921f-be51-4fa0-a720-c5500441fcbd"
authors = ["Sam Atman <atmanistan@gmail.com> and contributors"]
version = "0.1.1"

[compat]
Aqua = "0.8"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
